spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10
        one-indexed-parameters: true
  datasource:
    hikari:
      minimum-idle: 20
      maximum-pool-size: 20
      idleTimeout: 30000
server:
  port: 18080
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  shutdown: graceful

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  datadog:
    metrics:
      export:
        api-key: ${DATADOG_KEY}


---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        globally_quoted_identifiers: true
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 16379
      ssl:
        enabled: false
      token: random_token
server:
  port: 18184 # booking-api? ?? ??
aws:
  datasource:
    write:
      url: jdbc:postgresql://localhost:15432/nangpun
      username: master_user
      password: master_password
    read:
      url: jdbc:postgresql://localhost:15433/nangpun
      username: repl_user
      password: repl_password
auth-server:
  url: http://localhost:19000
booking:
  api:
    baseurl: http://localhost:18080
openapi:
  service:
    url: /
springdoc:
  api-docs:
    enabled: true
    path: /backend-service/v1
  swagger-ui:
    enabled: true
    path: /backend-service/swagger-ui/index.html # http://localhost:18184/backend-service/swagger-ui/swagger-ui/index.html
